### ISSUE TITLE
Crash when placing DBS (dimensional bridge stabilizer)   

### ISSUE THREAD

**Issue by beaverrac** [enhanced-portals/enhanced-portals#194]
I am playing the DNS tech pack on the AT launcher. I have added a few mods to it, (adventure backpacks, Advent of Ascension, legend gear and loot bags) and I am attempting to use enhanced portals V.3.0.9. Everything seemed to be working fine until I placed the DMS, as soon as I placed the first block it completely crashed my game and corrupted the save file until I removed the mod, in turn removing the block. Anyone having the same problem? And is there a fix? Thanks for the help!

**Comment by Zamajam** [comment]
I am having this same issue with the DBS block. I am using the HermitCraft Modsauce pack and I have updated a lot of the mods and added Thaumcraft and Necromancy. I am using v 3.0.9. All the other blocks in the pack work fine, it's only when I add the DBS block - the server crashes. I tried updating to Enhanced Portals V 3.1.0, but that won't even let me load the game.

**Comment by CJP8602** [comment]
I'm playing another modpack by the name of SBA technic pack 2 on the technic launcher (which may have more issues than the other mentioned packs) and I have had the same problem. on a multiplayer server I placed the DBS block down and I crashed my entire game and now whenever I try to reconnect to the server my game crashes again. I tried this on a singleplayer world, everything ran just fine until i placed a dbs block down. Also this was left in the console if it helps at all.



 [B#349]  [15:19:15] [Server thread/ERROR]: Encountered an unexpected exception
[B#349]  java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
[B#349]  	at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196) ~[MjAPI.class:?]
[B#349]  	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85) ~[MjAPI.class:?]
[B#349]  	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55) ~[MjAPI.class:?]
[B#349]  	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46) ~[MjAPI.class:?]
[B#349]  	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:159) ~[PowerHandler.class:?]
[B#349]  	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:145) ~[PowerHandler.class:?]
[B#349]  	at enhancedportals.tileentity.TileStabilizer.<init>(TileStabilizer.java:40) ~[TileStabilizer.class:?]
[B#349]  	at enhancedportals.block.BlockStabilizer.func_149915_a(BlockStabilizer.java:56) ~[BlockStabilizer.class:?]
[B#349]  	at net.minecraft.block.Block.createTileEntity(Block.java:1446) ~[aji.class:?]
[B#349]  	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850) ~[apx.class:?]
[B#349]  	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660) ~[apx.class:?]
[B#349]  	at net.minecraft.world.World.func_147465_d(World.java:451) ~[ahb.class:?]
[B#349]  	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206) ~[abh.class:?]
[B#349]  	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103) ~[abh.class:?]
[B#349]  	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
[B#349]  	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
[B#349]  	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
[B#349]  	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
[B#349]  	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
[B#349]  	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
[B#349]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
[B#349]  	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
[B#349]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
[B#349]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
[B#349]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
[B#349]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[B#349]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
